language: python
python:
    - "2.7"
# command to install dependencies
install: 
    - "source ./Envs/.env-example"
    - "pip install -r requirements.txt"
    - "python manage.py deploy"
# command to run tests
script: nosetests
