"""added join_core and attend_talks to User

Revision ID: 367e841c6c37
Revises: 5b240810633
Create Date: 2014-09-09 11:28:55.631782

"""

# revision identifiers, used by Alembic.
revision = '367e841c6c37'
down_revision = '5b240810633'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attend_talks', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('join_core', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_core')
    op.drop_column('users', 'attend_talks')
    ### end Alembic commands ###
