"""added User fields

Revision ID: e07cf08d32e
Revises: 4843e7282246
Create Date: 2014-06-30 16:44:37.487747

"""

# revision identifiers, used by Alembic.
revision = 'e07cf08d32e'
down_revision = '4843e7282246'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uniqname', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_uniqname'), 'users', ['uniqname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uniqname'), table_name='users')
    op.drop_column('users', 'uniqname')
    ### end Alembic commands ###
